### ISSUE TITLE
Error message on login - The Network host is not currently reachable

### ISSUE THREAD

**Issue by bizzychamps** [CAAPIM/Sample-App-MAS-iOS-Login-User-Authentication-And-Authorization#2]
Any idea why I might be getting this error message? I have set up the Keychain Access Groups and capabilities to match my company name. When I put a breakpoint on MASMAinViewController,  In 266, I  get the error message `error	NSError *	domain: @"com.ca.MASFoundation.localError:ErrorDomain" - code: 18446744073709550613	0x0000608000253470`

**Comment by BobbyWeber** [comment]
@bizzychamps can you provide a bit more info?
1. Did you do a pod update first?
2. Do you have a valid msso_config?

When I follow all the steps on the main readme (https://github.com/CAAPIM/Sample-App-MAS-iOS-Login-User-Authentication-And-Authorization/blob/master/README.md) I do not get any errors.

Please send more info on the steps above and/or a code snippet of exactly what you changed and I will try and replicate that here,

**Comment by bizzychamps** [comment]
looks like it an xcode update was in order.
